### ISSUE TITLE
how it should work?

### ISSUE THREAD

**Issue by dzmitry-lahoda** [cmoog/bech32#1]
tried
```
bash-5.1$ nix run .#bech32 -- --decode "centauri12smx2wdlyttvyzvzg54y2vnqwq2qjatescq89n" --prefix centauri
```

go 
```
T6e9�"��        �E*E2`p uy
```

**Comment by cmoog** [comment]
My best guess is that your string is encoded with the [BIP-0350](https://github.com/bitcoin/bips/blob/master/bip-0350.mediawiki) variant. This CLI is currently hard-coded to the [BIP-0173](https://github.com/bitcoin/bips/blob/master/bip-0173.mediawiki) variant.

Open to parameterizing that value through a flag though.

Otherwise, it seems like it's working as expected and your encoded value is invalid UTF-8.

**Comment by cmoog** [comment]
Open to parameterize that value through a flag though.
